### ISSUE TITLE
Typo on newsletter page

### ISSUE THREAD

**Issue by satsie** [bitcoin-dev-project/decoding-bitcoin#35]
I'm sorry, I'd make a PR request if I had the bandwidth but instead I'm filing an issue. On this page, https://bitcoindevs.xyz/decoding/newsletter, there is a typo on the word "ENOUGH"

![Screenshot from 2024-11-21 14-32-27](https://github.com/user-attachments/assets/1499922e-7762-4e4b-bcdc-8b6056a5141c)

**Comment by jrakibi** [comment]
Thanks @satsie, fixed here https://github.com/bitcoin-dev-project/decoding-bitcoin/pull/36
